In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6])

In [3]:
arr

array([1, 2, 3, 4, 5, 6])

In [4]:
arr+1

array([2, 3, 4, 5, 6, 7])

In [5]:
arr-1

array([0, 1, 2, 3, 4, 5])

In [6]:
arr*5

array([ 5, 10, 15, 20, 25, 30])

In [7]:
arr/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. ])

In [9]:
arr**2

array([ 1,  4,  9, 16, 25, 36])

In [10]:
arr**3

array([  1,   8,  27,  64, 125, 216])

In [12]:
arr = arr+1
# now this line will change the array

In [13]:
arr

array([3, 4, 5, 6, 7, 8])

In [ ]:
# find max in arr

In [14]:
arr.max()

8

In [15]:
arr.min()

3

In [18]:
arrr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

In [22]:
arrr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
arrr.max(axis = 0)
# here we will get the max element in each column

array([7, 8, 9])

In [26]:
arrr.max(axis=1)
# here we will get the max element in each row

array([3, 6, 9])

In [27]:
arrr.min(axis = 0)

array([1, 2, 3])

In [28]:
arrr.min(axis = 1)

array([1, 4, 7])

In [29]:
arrr.sum()

45