In [1]:
import numpy as np

In [2]:
arr1 = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
arr2 = np.array([[9,8,7],
                 [6,5,4]
                 ,[3,2,1]])

In [3]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
arr2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [5]:
# adding 2 arrays, no different shapes can be added
arr1+arr2

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [6]:
arr1-arr2

array([[-8, -6, -4],
       [-2,  0,  2],
       [ 4,  6,  8]])

In [7]:
arr1*arr2

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [8]:
arr1.dot(arr2)
# dot operation

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [9]:
arr2.dot(arr1)

array([[ 90, 114, 138],
       [ 54,  69,  84],
       [ 18,  24,  30]])

In [10]:
# indexing in array
arr = np.array([1,2,3,4,5])

In [11]:
arr[:]
# this will give us 1st index

array([1, 2, 3, 4, 5])

In [12]:
arr[:3]
# first 3 elements

array([1, 2, 3])

In [13]:
arr[2:]
#elements after index 1

array([3, 4, 5])

In [14]:
arr1[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
arr1[:,:1]
# first element of every row

array([[1],
       [4],
       [7]])

In [18]:
arr1[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
arr1[:,1:2]

array([[2],
       [5],
       [8]])

In [20]:
# middle element
arr1[1:2, 1:2]

array([[5]])

In [21]:
arr1[1:,1:]

array([[5, 6],
       [8, 9]])