In [1]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import numpy as np

In [4]:
lst = [1,2,3]

In [5]:
lst

[1, 2, 3]

In [6]:
type(lst)

list

In [7]:
arr = np.array(lst)

In [8]:
arr

array([1, 2, 3])

In [9]:
type(arr)

numpy.ndarray

In [10]:
arr.ndim

1

In [11]:
arr.shape

(3,)

In [12]:
arr.size

3

In [13]:
arr.dtype

dtype('int64')

In [16]:
zeros = np.zeros((3,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
ones = np.ones((6,3))

In [18]:
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])