In [2]:
import numpy as np

In [16]:
arr = np.random.random((3,4))

In [9]:
if np.random.random() > 0.5:
  print("Run")
else:
  print("Don't run the function")

Run


In [10]:
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [12]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [13]:
np.linspace(1,7,10)

array([1.        , 1.66666667, 2.33333333, 3.        , 3.66666667,
       4.33333333, 5.        , 5.66666667, 6.33333333, 7.        ])

In [ ]:
# linspace takes last parameter as how many values you want between the first 2 parameter including both the parameter

In [17]:
np.reshape(arr, (4,3))

array([[0.95214471, 0.28703579, 0.20220506],
       [0.04040527, 0.2445079 , 0.81119387],
       [0.59336583, 0.74699511, 0.43809282],
       [0.85193902, 0.29831895, 0.45092787]])

In [18]:
np.reshape(arr, (6,2))

array([[0.95214471, 0.28703579],
       [0.20220506, 0.04040527],
       [0.2445079 , 0.81119387],
       [0.59336583, 0.74699511],
       [0.43809282, 0.85193902],
       [0.29831895, 0.45092787]])

In [19]:
arr.flatten()


array([0.95214471, 0.28703579, 0.20220506, 0.04040527, 0.2445079 ,
       0.81119387, 0.59336583, 0.74699511, 0.43809282, 0.85193902,
       0.29831895, 0.45092787])

In [ ]:
#flatten function helps to convert the array into 1D